INSERT INTO Menu_Item (name, description, image, price)
VALUES ('VEG MEAL OPTION (Medium)', 
  'Total TEN containers featured veg curries,
  SIXTEEN Whole Wheat Chappatis,
  TWO Large Basmati Pulao Rice or Steam Rice,
  Dessert,
  Pickle,
  Chutney',
  'https://bombaypalacetoronto.com/tiffin/images/VegMealpic2.jpg',
  '95.00'
);

INSERT INTO Menu_Item (name, description, image, price)
VALUES ('NON-VEG MEAL (Large)', 
  'Total FIFTEEN containers of featured curries
  Includes THREE Non-Veg,
  TWELVE Veg Containers
  TWENTY Whole wheat chappatis,
  THREE Large Basmati Pulao Rice or Steam Rice
  Dessert,
  Pickle, 
  Chutney,
  Salad',
  'https://bombaypalacetoronto.com/tiffin/images/NonVegMealpic3.jpg',
  '141.25'
);

INSERT INTO Menu_Item (name, description, image, price)
VALUES ('MEAT LOVERS (Small)', 
  'FOUR curry dishes in total,
Any TWO Featured Non Veg Dishes
Any TWO featured Veg Dishes
ONE Large Rice ( Steam or Pulao)
FOURTEEN Chappatis
Featured Dessert or Salad
Pickle and or Chutney',
  'https://bombaypalacetoronto.com/tiffin/images/NonVegMealpic3.jpg',
  '74.58'
);